### ISSUE TITLE
Question: How to render a ROP node?

### ISSUE THREAD

**Issue by aryan-mann** [alexxbb/hapi-rs#13]
Hey @alexxbb, thanks a lot for working on this 🎉 !
Would you know if there's currently a way to send a render command to a ROP node (`/out`)? For context, I'm trying to output a GLTF file from a HIP. I've seen that it's possible via the Python API here: [hou – RopNode](https://www.sidefx.com/docs/houdini/hom/hou/RopNode.html) but I couldn't figure out how to do it via Rust/the Houdini C Engine API.

Let me know if you have any ideas if this is possible. Cheers!

**Comment by alexxbb** [comment]
Hey Aryan,
If by "send a render command to a ROP node" you mean pressing the Render button on it, then it's super easy. One simple way is if you export that button to your HDA parameters, then you can do:
```rust
if let Parameter:Button(parm) = node.parameter("render")? {
    parm.press_button()?
}
```
If you however build the nodes dynamically or have the ROP node somewhere inside you HDA, you can always find the node using the find methods. For example:

```rust
let handles = asset.find_children_by_type(NodeType::Rop, NodeFlags::Any, true).expect("List of nodes");
// assume we found one node 
let node = handles[0].to_node(session).unwrap();
if let Parameter:Button(parm) = node.parameter("render")? {
    parm.press_button()?
}
```

Let me know if that works.
Cheers.

**Comment by aryan-mann** [comment]
🥇 That indeed did work @alexxbb, thanks for the detailed response.
