### ISSUE TITLE
Linking at runtime/releasing app as OSS

### ISSUE THREAD

**Issue by grilme99** [alexxbb/hapi-rs#20]
I'm investigating how to release and bundle an engine integration as a release on GitHub. I need clarification on how to link against HAPI statically in GitHub CI or dynamically at runtime. What would be the best/correct approach if I want users to be able to download an executable and immediately start using the integration?

**Comment by alexxbb** [comment]
For this, you need a Houdini install in GitHub CI (most likely in a docker), then you just export the HFS env variable and the crate should build fine. The users of your executable will then need to have a Houdini installed as well and set the environment with the Houdini libraries, i.e. roughly:
* `PATH=%PATH%;%HFS%/bin` on Windows
* `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HFS/dsolib` on Linux 
* `DYLD_LIBRARY_PATH=[path to houdini install]/dsolib` on Mac

**Comment by grilme99** [comment]
Thank you!
