### ISSUE TITLE
Support Houdini v20

### ISSUE THREAD

**Issue by luxalpa** [alexxbb/hapi-rs#22]
I tried using this in Houdini v20 and I'm getting `STATUS_HEAP_CORRUPTION` when I try to use `NumericArrayAttr<u8>::get`

**Comment by alexxbb** [comment]
I will have a look at this shortly. Thanks.

**Comment by alexxbb** [comment]
While working on upgrading the library to support H20, I discovered a bug in HARS (Houdini Engine Server) which I submitted to SideFX, and they said that the fix will be available in the next Houdini build (early next week). I will try to test it and release the new version next week.

**Comment by alexxbb** [comment]
The new version `0.10.0` has been released with Houdini 20 support. Note that `Houdini 20.0.625` is the minimal supported version.

**Comment by luxalpa** [comment]
Very nice, thank you!
