### ISSUE TITLE
array::DataArray type not exported

### ISSUE THREAD

**Issue by luxalpa** [alexxbb/hapi-rs#8]
The function [attribute::NumericArrayAttr::get](https://docs.rs/hapi-rs/latest/hapi_rs/attribute/struct.NumericArrayAttr.html#method.get) returns a `DataArray`, however the type is not being exported from the crate. It is `pub`, but unfortunately the `array` module in which it sits is private.

I have a snipped that I would like to move into its own function, but because of the missing type I cannot put it into the functions return type!

```rs
    let attrib = geo
        .get_attribute(part.part_id(), AttributeOwner::Point, "boneCapture_data")?
        .ok_or(anyhow::anyhow!(
            "Asset does not have a boneCapture attribute"
        ))?;

    let attrib = attrib
        .downcast::<NumericArrayAttr<f32>>()
        .ok_or(anyhow::anyhow!(
            "Asset has incorrect boneCapture_data attribute"
        ))?;

    let arr = attrib.get(part.part_id())?; // <-- Problem. arr type cannot be named
```

In this case I can workaround the problem, but I thought I'd report it here.

**Comment by alexxbb** [comment]
Ah yes, let me push a fix for that.

**Comment by alexxbb** [comment]
Pushed 0.5.3 with the fix.
